name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - run: ./gradlew clean test
        name: Build

      - name: Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        #id: allure-report
        with:
            allure_results: allure-results
            #gh_pages: gh-pages
            #allure_report: allure-report
            allure_history: allure-history
            keep_reports: 20