name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      #- uses: browser-actions/setup-chrome@v1
      - uses: Xotabu4/selenoid-github-action@v2
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - run: ./gradlew clean test
        name: Build

      - name: Copy History
        uses: actions/checkout@v2
        if: always()
        with:
          ref: gh-pages
          path: gh-pages


      - name: Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
            allure_results: build/allure-results
            gh_pages: gh-pages
            allure_report: allure-report
            allure_history: allure-history
            keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history